name: Build and Publish Docs

on:
  release:
    types: [published]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pdoc
        run: pip install pdoc3
      - name: Build docs
        run: pdoc --html --output-dir docs src/fputils
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/fputils

  publish-docs:
    needs: build-docs

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
